name: Build and Push Prefect Container

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Snowflake registry
        run: echo "${{ secrets.SNOWFLAKE_PASSWORD }}" | docker login fbqxwjn-tz60398.registry.snowflakecomputing.com -u ${{ secrets.SNOWFLAKE_USER }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t prefect-orion-local:latest .

      - name: Tag and push to Snowflake
        run: |
          IMAGE_URI=fbqxwjn-tz60398.registry.snowflakecomputing.com/tutorial_db/data_schema/tutorial_repository/prefect-orion-local:latest
          docker tag prefect-orion-local:latest $IMAGE_URI
          docker push $IMAGE_URI
